apiVersion: v1
kind: Service
metadata:
  labels:
    app:  vote-app-ui
  name:  vote-app-ui
spec:
  type: NodePort
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app:  vote-app-ui
